### ISSUE TITLE
[Bug] Integration doesn't work with RouterOS 7.13 Beta

### ISSUE THREAD

**Issue by Foroxon** [tomaae/homeassistant-mikrotik_router#328]
## Describe the issue
Integration doesn't work

## How to reproduce the issue
1. Upgrade Router OS to 7.13 beta2 on device

## Expected behavior
It should work like on Router OS <7.13

## Software versions
 - Home Assistant version: HA 2023.11.2
 - Mikrotik Router integration version: v2.1.4
 - Mikrotik Hardware: RB5009UG+S+
 - RouterOS version: 7.13beta2

## Diagnostics data
  No

## Traceback/Error logs
Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
Integration: Mikrotik Router (documentation, issues)
First occurred: 14 листопада 2023 р. о 21:42:42 (660 occurrences)
Last logged: 12:16:05

Mikrotik 192.168.86.2 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by L2jLiga** [comment]
Did you tried to install "wireless" package as a workaround?
Since CAPsMAN now moved to this package it should work well

**Comment by YaoFei509** [comment]
> Did you tried to install "wireless" package as a workaround? Since CAPsMAN now moved to this package it should work well

wireless package will confilict with new wifi-qcom package. 
So it's better check whether CAPSMAX exists.

**Comment by L2jLiga** [comment]
So in wifi-qcom CAPsMAN renamed to CAPsMAX?
If so, then integration now have to check both in order to keep compatibility and provide new functionality

**Comment by Foroxon** [comment]
> So in wifi-qcom CAPsMAN renamed to CAPsMAX? If so, then integration now have to check both in order to keep compatibility and provide new functionality

No, as I understand "wireless" package was renamed to "wifi", so now CAPsMAN can be found on `interface wifi capsman`

<img width="187" alt="Screenshot 2023-11-22 at 11 18 25" src="https://github.com/tomaae/homeassistant-mikrotik_router/assets/925166/daab1851-39b1-4b23-9efe-50d19a79e17b">

**Comment by L2jLiga** [comment]
For ROS < 7.13: `/caps-man`
For ROS >= 7.13: `/interface/wifi/capsman` when wireless package installed

Is it correct?

**Comment by Foroxon** [comment]
Yes. But also it was totally rewritten. So there is no more `/interface/wifi/capsman/registration-table` as it was on `/caps-man/registration-table`.
Now it's common for local managed wifi and CAPsMAN managed wifi and located in `/interface/wifi/registration-table`.
It may be similar for other old caps-man functions.

**Comment by L2jLiga** [comment]
I'm glad that I decided to stay on 7.12.1 😅

**Comment by GlenWi** [comment]
I have this exact issue also.

2023-11-25 19:17:10.751 WARNING (SyncWorker_3) [homeassistant.components.mikrotik.hub] Mikrotik 192.168.88.1 failed to retrieve data. cmd=[/caps-man/interface/print] Error: no such command or directory (caps-man), no such command prefix
2023-11-25 19:17:10.753 WARNING (SyncWorker_3) [homeassistant.components.mikrotik.hub] Mikrotik 192.168.88.1 failed to retrieve data. cmd=[/interface/wireless/print] Error: no such command or directory (wireless), no such command prefix
2023-11-25 19:17:10.754 WARNING (SyncWorker_3) [homeassistant.components.mikrotik.hub] Mikrotik 192.168.88.1 failed to retrieve data. cmd=[/interface/wifiwave2/print] Error: no such command or directory (wifiwave2), no such command prefix
2023-11-25 19:17:14.211 ERROR (SyncWorker_5) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:17:29.026 ERROR (SyncWorker_0) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:17:42.597 ERROR (SyncWorker_8) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:18:05.791 ERROR (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:18:49.419 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:20:12.635 ERROR (SyncWorker_7) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:21:35.120 ERROR (SyncWorker_5) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:22:57.413 ERROR (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:24:20.032 ERROR (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

2023-11-25 19:25:42.635 ERROR (SyncWorker_7) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:27:05.064 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:27:40.629 ERROR (SyncWorker_9) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:27:48.116 ERROR (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:28:00.331 ERROR (SyncWorker_6) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:28:22.802 ERROR (SyncWorker_0) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:28:27.241 ERROR (SyncWorker_4) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:29:05.370 ERROR (SyncWorker_2) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:29:49.701 ERROR (SyncWorker_7) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:31:12.221 ERROR (SyncWorker_10) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2023-11-25 19:32:34.805 ERROR (SyncWorker_1) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.88.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by slackr31337** [comment]
I added a PR to fix this. (Fix for ros 7.13 wireless #332)

**Comment by Lieta2** [comment]
7.13 stable was released today.
Before 7.13 these existed:
/interface/wireless/
/caps-man/interface/
Starting from 7.13:
/interface/wifi/
/interface/wifi/capsman
/interface/wifiwave2 is alias to /interface/wifi

**Comment by fragtion** [comment]
The wireless package is now optional. Integration setup should be possible without wireless/capsman, but fails to initialize the device:
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/2876889/8bde16f6-5470-400b-880d-fbc6043fb41c)
Routeros v7.13 stable

**Comment by M0DDer** [comment]
I'm waiting for update

**Comment by VladimirV01** [comment]
I have the same issue. 

Upgraded to ROS 7.13 and the integration does not work.

**Comment by Yamaha0014** [comment]
Hi, After ugraded to 7.13 integration not connect to router. My router C53UiG+5HPaxD2HPaxD (Mikrotik AX3), We wait for update integration. Thenks for Your great job.

**Comment by vheneraliuk** [comment]
Why does it take so long to fix this issue? I can't use this integration for about two months now.

**Comment by GlenWi** [comment]
Same here.  Maybe it's a difficult problem to solve?  It looks pretty embedded in Mikrotik's roadmap as 7.14 beta is using the same structure now.

**Comment by M0DDer** [comment]
It Works even at 7.14 !

With this file, added manualy
[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)

and this changes
[[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107)

**Comment by teddyhalim** [comment]
> It Works even at 7.14 !
> 
> With this file, added manualy from (you need to replace file) [custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)
> 
> and this changes (you need to add 2 lines) [[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)]([#332 (comment)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107))
> 
> Работает даже в 7.14 !
> 
> Скачать и заменить файл [custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)
> 
> Добавить две строчки в другой файл [[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)]([#332 (comment)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107))

which coordinator.py do I need to download and replace? the 1st one or the 2nd one? TIA

**Comment by ranrinc** [comment]
> It Works even at 7.14 !
> 
> With this file, added manualy from (you need to replace file) [custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)
> 
> and this changes (you need to add 2 lines) [[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)]([#332 (comment)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107))
> 
> Работает даже в 7.14 !
> 
> Скачать и заменить файл [custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)
> 
> Добавить две строчки в другой файл [[custom_components/mikrotik_router/coordinator.py](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332/files/1bbedfaa8b411553876b8cb9454d925bb284a2b2#diff-4a39d7d77d0cdde5dca3c20452a70e10c9b684d6b94524b0e46a71389d109572)]([#332 (comment)](https://github.com/tomaae/homeassistant-mikrotik_router/pull/332#issuecomment-1890752107))

Which coordinator.py do I need to download/replace 1st or 2nd one? TIA

**Comment by L2jLiga** [comment]
Actually you have 2 more options to install version from #332 

<details>
<summary>Option 1 - Like HACS manual install</summary>

Just follow [HACS manual install instruction](https://github.com/claytonjn/hacs/blob/master/docs/installation/manual.md), except steps 2 and 3

download zip file from this specific branch on repo [short link](https://github.com/slackr31337/homeassistant-mikrotik_router/tree/ros-7.13) via "Code" -> "Download zip"
![image](https://github.com/tomaae/homeassistant-mikrotik_router/assets/11780854/69bbdacd-1624-46c3-93bf-cff10895c6d0)
</details>

<details>
<summary>Option 2 - Install via Shell</summary>

```shell
~/config$ cd custom_components/
~/config/custom_components$ rm -Rf mikrotik_router
~/config/custom_components$ curl https://codeload.github.com/slackr31337/homeassistant-mikrotik_router/zip/refs/heads/ros-7.13 -o master.zip
~/config/custom_components$ unzip master.zip
~/config/custom_components$ mv homeassistant-mikrotik_router-ros-7.13/custom_components/mikrotik_router/ .
~/config/custom_components$ rm -Rf homeassistant-mikrotik_router-ros-7.13/
~/config/custom_components$ rm -Rf master.zip
~/config/custom_components$ ls -l
total 4
drwxrwxr-x 3 user user  4096 Dec 27 14:28 mikrotik_router
```
</details>

**Comment by mrbaja** [comment]
After using @M0DDer 's fix, integration is working again, however number of wired clients is not working, it always reports 0. 
Is anyone else having the same issue?

**Comment by GlenWi** [comment]
Yes, I have the same issue - 3 wired clients but the integration says 0

**Comment by tomaae** [comment]
are you on latest master?

**Comment by FrankGiesecke** [comment]
@tomaae please, can you explain how to switch to Master in HACS?
I‘ve tried to select master from the version dropdown, but it doesn‘t affect the version to install.

**Comment by tomaae** [comment]
it no longer works, HACS decided letting zip distributed integrations to install master was a bug.
You will have to download and install it manually

**Comment by FrankGiesecke** [comment]
@tomaae Thanks for your reply. Install it manually work. Now I can connect to my MikroTik. 🙏

**Comment by FrankGiesecke** [comment]
@tomaae Did you plan to release a new version?

**Comment by tomaae** [comment]
of course, but I need time. new version wont be just about mikrotik features

**Comment by Yamaha0014** [comment]
Today Mikrotik relase new stable version 7.14, has anyone already tested if the integration still works?

**Comment by nico282** [comment]
> of course, but I need time. new version wont be just about mikrotik features

Sorry I don’t understand. You are going to leave the non working version of the integration as the latest release? Why?

**Comment by Roving-Ronin** [comment]
> Today Mikrotik relase new stable version 7.14, has anyone already tested if the integration still works?

@Yamaha0014 Updated CCR2004 to 7.14 and HA 2024.2.4 appears to be working fine with it.

**Comment by FrankGiesecke** [comment]
> of course, but I need time. new version wont be just about mikrotik features

Oh, but why?  
The current version is broken and can no longer be used with up-to-date MikroTik devices.  
IMHO: It would make sense to release a new version. This will avoid new users to run into problems.

**Comment by Yamaha0014** [comment]
> > Today Mikrotik relase new stable version 7.14, has anyone already tested if the integration still works?
> 
> @Yamaha0014 Updated CCR2004 to 7.14 and HA 2024.2.4 appears to be working fine with it.

Ok, Ax3 working, too. B. R. Yamaha0014

**Comment by Axotopia** [comment]
RB5009UPr+S+       working w/ RouterOS 7.14
L009UiGS-2HaxD    still getting ..'Failed setup, will retry'

**Comment by lafriks** [comment]
Any chance of new version release?

**Comment by Korvenwin** [comment]
I'm using Mikrotik 7.14.1 and HAss 2024.3.1 and I'm having same issue.

It works fine until I removed it and then added again.

I suspect that it was because he integration was configured while RouterOS was on v6.x and after updating to 7.x it worked.

Now as a new setup with v7.14 it can't start the configuration.

**Comment by fencer** [comment]
installed this today and got stuck because of this issue.

**Comment by tomaae** [comment]
> I'm using Mikrotik 7.14.1 and HAss 2024.3.1 and I'm having same issue.
> 
> It works fine until I removed it and then added again.
> 
> I suspect that it was because he integration was configured while RouterOS was on v6.x and after updating to 7.x it worked.
> 
> Now as a new setup with v7.14 it can't start the configuration.
> 
> I would be very very grateful to @tomaae if he/she could find some time to fix this error. The integration is GREAT

pretty sure it already works on master

**Comment by Korvenwin** [comment]
I'm still getting this:

"Mikrotik 192.168.X.X error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix"

**Comment by tomaae** [comment]
are you sure you are on most recent master version?

**Comment by Korvenwin** [comment]
I'm using most recent version on HACS: v2.1.4

**Comment by tomaae** [comment]
yes, I'm talking about master, not v2.1.4

**Comment by Korvenwin** [comment]
Please, let me know how to install master.

**Comment by lafriks** [comment]
Same for me, does not seems to be able to select master as install version in HACS

**Comment by tomaae** [comment]
HACS decided to remove that option. Only way to get master is to install it manually.
Another option is to wait for release.

**Comment by Roving-Ronin** [comment]
Doesn't work, with 'Master' manually installed 

RouterOS 7.14.2

HA Core                               2024.4.0
HA Supervisor                      2024.03.1
HA Operating System          12.1
HA Frontend                        20240403.1

---------------------------------------------------------
(Same) Error Message:


This error originated from a custom integration.

Logger: custom_components.mikrotik_router.mikrotikapi
Source: custom_components/mikrotik_router/mikrotikapi.py:95
integration: Mikrotik Router (documentation, issues)
First occurred: 12:19:06 (20 occurrences)
Last logged: 12:34:29

Mikrotik 10.x.y.z error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

**Comment by tomaae** [comment]
I will need to see debugs for this.

**Comment by Roving-Ronin** [comment]
Hi @tomaae is this what you need?

[home-assistant_mikrotik_router_2024-04-06T04-23-54.434Z.log](https://github.com/tomaae/homeassistant-mikrotik_router/files/14892279/home-assistant_mikrotik_router_2024-04-06T04-23-54.434Z.log)

**Comment by tomaae** [comment]
Are you sure this is master? Version debugs that were added to master recently are missing.

**Comment by nico282** [comment]
> HACS decided to remove that option. Only way to get master is to install it manually. Another option is to wait for release.

Why don’t you build a release and make life easier for everyone? 

The latest release is not working with the current RouterOS. Multiple people tested the changes and confirmed it is working. What’s missing?

**Comment by tomaae** [comment]
> > HACS decided to remove that option. Only way to get master is to install it manually. Another option is to wait for release.
> 
> Why don’t you build a release and make life easier for everyone?
> 
> The latest release is not working with the current RouterOS. Multiple people tested the changes and confirmed it is working. What’s missing?

Because I wont release until I test everything myself and confirm that its working on all version.
When it comes to mikrotik, only very small minority upgrades to latest. Large percentage are still on 6.49.
Those who upgraded to latest can always use master, its just too bad HACS removed option to install master.

**Comment by Korvenwin** [comment]
> > > HACS decided to remove that option. Only way to get master is to install it manually. Another option is to wait for release.
> > 
> > 
> > Why don’t you build a release and make life easier for everyone?
> > The latest release is not working with the current RouterOS. Multiple people tested the changes and confirmed it is working. What’s missing?
> 
> Because I wont release until I test everything myself and confirm that its working on all version. When it comes to mikrotik, only very small minority upgrades to latest. Large percentage are still on 6.49. Those who upgraded to latest can always use master, its just too bad HACS removed option to install master.

And, what about two releases in HACS? Is this very complicated?

About installing master, should I copy files on "/master/custom_components/mikrotik_router/" overwriting the old ones or should I do anything more?

**Comment by tomaae** [comment]
It always offers to install latest update, so that introduces risk. There are actually few that use this integration in ISP setting, so not well tested update could mess thigs up for them really badly.

I would personally clone the git, but downloading repo zip and overwriting it will do just fine.

I know my development style is not for everyone's liking, but it ensures higher quality and fewer issues. I juggle several free projects (not just 4 HA integrations you see here) mostly alone with very little free time right now.
So I will get it done and working well, it will just not be fast.

**Comment by FrankGiesecke** [comment]
We can truely understand your opinion.

But not every user of HA is familiar in using git (or GitHub).

There is also the possibility to release a beta version.

It would be great if you use this way to give all users of your integration an easy option to run patched versions.

**Comment by Roving-Ronin** [comment]
Hi @tomaae is this what you need? Reapplied the files I got from master zip download.

[home-assistant_mikrotik_router_2024-04-07T08-10-54.264Z.zip](https://github.com/tomaae/homeassistant-mikrotik_router/files/14896404/home-assistant_mikrotik_router_2024-04-07T08-10-54.264Z.zip)

**Comment by tomaae** [comment]
you need to restart HA after changing any files

**Comment by GlenWi** [comment]
Hi - Do you have any timeframe in mind as to when a version that works with the current version of Mikrotik routers will be released?

**Comment by FrankGiesecke** [comment]
When will you release a new version?

Consumers won't use `master`. We rather want use releases.

**Comment by casperjjordaan** [comment]
Guys please! Why is this taking so long? I need this to work.

**Comment by GlenWi** [comment]
It seems this integration is not really supported any longer, shame as it is very useful.  I am on 715 RC4 now.....

**Comment by Yamaha0014** [comment]
Hi, version 7.15 was released yesterday, has anyone tested the integration work?

**Comment by Korvenwin** [comment]
It is working for me

**Comment by Real-Ztrawberry** [comment]
For what it's worth, I managed to get the integration working on existing instances as well as a new installation by:
* Ensuring beta features are disabled in HACS
* Use Redownload in HACS, wait for the versions to be populated, select Master at the bottom of the list. Wait a bit
* Reboot HA (not just a quick restart)
* Do above again and again until it works

**Comment by riddley** [comment]
@tomaae 
Would you please communicate your intentions with the community? Are you interested in help or new maintainers? A little communication would be really appreciated.

**Comment by Yamaha0014** [comment]
> It is working for me. EDIT: I'm using the master version.

ok, I updated ax3 to 7.15 and working ok, I have integration with copy files by ftp.

**Comment by FrankGiesecke** [comment]
There is still no new version.

I'm running on master for 9 month now and can confirm, that everything is working fine.

So I'll bagging you @tomaae  release a version.

**Comment by riddley** [comment]
Inching up on a year since the last release. I think it might be time to admit to ourselves that this software has been abandoned.

**Comment by FrankGiesecke** [comment]
@riddley but the commits in the main brach looks like the work is still in progress

**Comment by SkeLLLa** [comment]
Mikrotiks now have native mqtt integration. So in theory all the necessary starts and switches could be managed by a collection of mikrotik scripts that listen/publish mqtt messages. The drawback is that there will be a need to manually setup proper sensor units, etc.

**Comment by Korvenwin** [comment]
MQTT is a great idea!!

**Comment by Onepamopa** [comment]
Errors out on CCR2994 - it's a model without any wireless capabilities.
Why does the integration ask for capsman in the first place, especially if capsman is ***OFF*** ?

**Comment by FrankGiesecke** [comment]
> For those who's interested in mqtt, there's a repo: https://github.com/Xrlls/MikroTik-Home-Assistant-MQTT-telemetry. It doesn't have a lot of functions, but it has good enough set for monitoring your router.
> 
> @Korvenwin FYI.

Cool, I'll test this. The main use case for me is to fetch statistics about the uplink interfaces (rx/tx).
The only thing I will miss is the opportunity to update the mikrotik devices direkt from HA.

**Comment by herijaya** [comment]
2024-08-29 13:37:12.191 DEBUG (SyncWorker_10) [custom_components.mikrotik_router.mikrotikapi] API query: /caps-man/registration-table
2024-08-29 13:37:12.194 ERROR (SyncWorker_10) [custom_components.mikrotik_router.mikrotikapi] Mikrotik 192.168.57.1 error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix
2024-08-29 13:37:12.196 DEBUG (MainThread) [custom_components.mikrotik_router.coordinator] Finished fetching Mikrotik data in 1.531 seconds (success: False)

**Comment by Onepamopa** [comment]
To get rid of the capsman issue, I changed coordinator.py, at least now the integration works.

        elif 0 < self.major_fw_version >= 7:
            self.support_ppp = True
            self.support_wireless = False
            if "wifiwave2" in packages and packages["wifiwave2"]["enabled"]:
                self.support_wifiwave2 = True
                self.support_capsman = False
            else:
                self.support_wifiwave2 = False
                self.support_capsman = False

**Comment by ilexpl01** [comment]
> To get rid of the capsman issue, I changed coordinator.py, at least now the integration works.
> 
> ```
>     elif 0 < self.major_fw_version >= 7:
>         self.support_ppp = True
>         self.support_wireless = False
>         if "wifiwave2" in packages and packages["wifiwave2"]["enabled"]:
>             self.support_wifiwave2 = True
>             self.support_capsman = False
>         else:
>             self.support_wifiwave2 = False
>             self.support_capsman = False
> ```

It did not work 4 me :(

ros: "7.15.3"

**Comment by Onepamopa** [comment]
I haven't added any wireless packages (the router doesn't have wireless anyways)

**Comment by FrankGiesecke** [comment]
Not stale!

**Comment by Real-Ztrawberry** [comment]
A major problem is with the new HACS 2.x you cannot select master any longer. So impossible to get the integration to work on new HA installations. It is now 326 days since 1st reported, wish there was something we could do to help advance the resolution.

**Comment by FrankGiesecke** [comment]
Thai issue won't be closeable until a new version is released.

**Comment by Tipalo** [comment]
+1   running ROS 7.16.1 stable

**Comment by FrankGiesecke** [comment]
This issue is Not stale

**Comment by ounyai** [comment]
I am getting the error error while building list for path /caps-man/registration-table : no such command or directory

**Comment by namadori** [comment]
I believe this project is now dead. It's broken since over one year and last commit was almost 6 months ago.
Can somebody knowledgeable just fork this and apply the changes that were already tested in this thread, so we can move over?

**Comment by Onepamopa** [comment]
Probably he just needs to create a new release.
The modification I made are @ version v.2.1.4 and are working, there are changes to the file by the developer after that, but not a release.

I'll try to test the latest version manually in HA when I get some free time.

**Comment by ResolvITAustralia** [comment]
Maybe we can try to contact him via his website and ask him if he can assist us all. Will give it a go.

**Comment by p0wertiger** [comment]
Still not solved

**Comment by usama-liaqat** [comment]
still not solved

**Comment by mschabhuettl** [comment]
@tomaae do you need a Co-Maintainer? I'd be glad to contribute! Cheers!

**Comment by fragtion** [comment]
> @tomaae do you need a Co-Maintainer? I'd be glad to contribute! Cheers!

Are you ready to tackle the workload? With bugs like #328 that are still outstanding, would you realistically have any idea to resolve these, and have the time to do so?

**Comment by namadori** [comment]
> The developer (@tomaae) is still active (they responded to my issue https://github.com/tomaae/homeassistant-mikrotik_router/issues/386 today in fact) - so the project isn't totally abandoned. There's just a lack of community support to fix bugs.

I would say "alive", not "active". The last significant commit is almost one year ago, then only a couple really minor ones.
You say there is a lack of community support, but the PR for this specific issue has been sent by a contributor on december 2023. The missing step is building a release, but only the mantainers can do that.

**Comment by ResolvITAustralia** [comment]
Let's be patient, I am sure @tomaae will be back when they have time.

**Comment by quantum-fc101** [comment]
+1

**Comment by Lieta2** [comment]
Not stale.

**Comment by hoolea** [comment]
Not stale.

Mikrotik error while building list for path /caps-man/registration-table : no such command or directory (caps-man), no such command prefix

A temporary solution, you can make the user write rights, but we get an error: Mikrotik user has does not have insufficient access rights. Integration functionality will be limited.

**Comment by Zarox666** [comment]
Is there any solution to this yet?

With the suggested workarounds from [Not work with firmware 7.17](https://github.com/tomaae/homeassistant-mikrotik_router/issues/403) I was able to at least get my integration working again on two hAP ac3.
But my new hAP ax3 does not have any "Wireless" in the WebFig at all.. just "WiFi" and its not reporting any Device Trackers for Wireless Devices.
Which not only makes the integration useless, but also causes great pain, as none of the presence detection still works and that would be a major rework/overhall to do it entirely different, without the help of the Mirkrotik routers.

Or has anyone found a working HomeAssistant Mikrotik Integration yet?

**Comment by mschabhuettl** [comment]
> > @tomaae do you need a Co-Maintainer? I'd be glad to contribute! Cheers!
> 
> Are you ready to tackle the workload? With bugs like #386 that are also still outstanding, would you realistically have any idea how to troubleshoot & resolve these, and have the time to do so?
> 
> The developer (@tomaae) is still active (they responded to my issue #386 today in fact) - so the project isn't totally abandoned. There's just a lack of community support to fix bugs.
> 
> Whoever takes ownership of this project must be capable of doing some catch-up otherwise there's no point transferring the rights, surely?  It's an open-source project after all, so nothing is stopping anyone from fixing any of the existing bugs.
> 
> With that said, resolution of this specific issue (#328) is long overdue now, with a community patch already provided (the patch provided by @Onepamopa works). Would be nice if that could be committed, at least.

@fragtion I completely agree that whoever takes over (or co-maintains) the project needs to be capable of keeping up with outstanding issues and bug fixes.

It’s good to hear that @tomaae is still somewhat active, as I wasn’t sure about the current status. However, as you pointed out, some critical issues—like this one (#328)—have been open for quite a while, despite a working patch being available. That’s why I believe we should discuss a more structured approach to community contributions.

Whether through co-maintainership or an organized community-driven fork, the goal should be to ensure that essential fixes like this one are reviewed and merged in a timely manner. Right now, we have contributors willing to help, but without an active maintainer to review and merge changes, progress is slow.

If @tomaae is open to a co-maintainer, that would be great. Otherwise, we should explore alternatives to keep development moving forward.

**Comment by tomaae** [comment]
isnt this issue actually solved already?

**Comment by Onepamopa** [comment]
> isnt this issue actually solved already?

If it is - there isn't a new build/release available..

**Comment by Lieta2** [comment]
Not stale.

**Comment by KaRLiKCZ** [comment]
It still doesn't work with new version of Mikrotik

**Comment by samuellazea** [comment]
This is not stale

**Comment by mschabhuettl** [comment]
Issue is not stale, but the project is... :-(

**Comment by mschabhuettl** [comment]
Not stale

**Comment by mschabhuettl** [comment]
Not stale!

**Comment by tomaae** [comment]
already fixed in master

**Comment by Onepamopa** [comment]
> already fixed in master

![Image](https://github.com/user-attachments/assets/6d1e6dc8-f7bd-415e-8bde-467d3e4ad737)

So, not fixed yet.

**Comment by mschabhuettl** [comment]
Not fixed. You need to push a new release

**Comment by JKtechhw** [comment]
@mschabhuettl New release [v2.2](https://github.com/tomaae/homeassistant-mikrotik_router) was made yesterday and it works with version 7.13 and later.

**Comment by mschabhuettl** [comment]
@JKtechhw hell yeah... Thank you
