### ISSUE TITLE
[Bug] HA may hang when user does not have correct permissions

### ISSUE THREAD

**Issue by tomaae** [tomaae/homeassistant-mikrotik_router#80]
Reported by @i-o-m-a :
There is small issue with the addon (i think with addon in general), if mikrotik user that configured with home assistant integration does not have enough permissions and any of integration switches triggered, HA becomes unusable until restart (for example: "ha core restart")...

**Comment by i-o-m-a** [comment]
The same issue with kid-control option.

**Comment by tomaae** [comment]
can you give me the error?
Not sure why such error is not captured, it should be.

**Comment by i-o-m-a** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mikrotik_router/mikrotikapi.py:267
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:43:24 (1 occurrences)
Last logged: 9:43:24

[547759424080] not enough permissions (9)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/config/custom_components/mikrotik_router/switch.py", line 595, in async_turn_off
    self._ctrl.set_value(path, param, value, mod_param, mod_value)
  File "/config/custom_components/mikrotik_router/mikrotik_controller.py", line 305, in set_value
    return self.api.update(path, param, value, mod_param, mod_value)
  File "/config/custom_components/mikrotik_router/mikrotikapi.py", line 267, in update
    for tmp in response:
  File "/usr/local/lib/python3.8/site-packages/librouteros/api.py", line 103, in __iter__
    yield from self('print')
  File "/usr/local/lib/python3.8/site-packages/librouteros/api.py", line 106, in __call__
    yield from self.api(
  File "/usr/local/lib/python3.8/site-packages/librouteros/api.py", line 28, in __call__
    yield from self.readResponse()
  File "/usr/local/lib/python3.8/site-packages/librouteros/api.py", line 69, in readResponse
    raise traps[0]
librouteros.exceptions.TrapError: not enough permissions (9)

**Comment by tomaae** [comment]
Thanks. I think this should be fixable. I will have a look into this later today.

**Comment by tomaae** [comment]
Should be fixed now

**Comment by tomaae** [comment]
Ok, fixed. That was strange behavior

**Comment by i-o-m-a** [comment]
Thank You!
Switch is working ok!
But now other issue :)  Sensor still showing "Disabled" status, even switch show "Enabled". 


![image](https://user-images.githubusercontent.com/76471219/103266661-c43bde00-49b8-11eb-857b-37a18507bee7.png)

**Comment by tomaae** [comment]
Is it only with PPP sensors, or other binary sensors as well?

**Comment by i-o-m-a** [comment]
Sorry, my fault. No issues. Looks like need to take a cup of coffee :))))

**Comment by tomaae** [comment]
hehe, enjoy your coffee ;)
